import { readFileSync, readdirSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";
import { describe, expect, it } from "vitest";

/**
 * Proves #1022 — no shopper-facing file can reach the internal KMS corpus except through
 * `lib/public-docs.ts`.
 *
 * `app/(admin)/staff/runbook/docs.ts` is generated by `kms:build-index` and exports every KMS
 * article, internal ones included. `/help` imported it directly, filtered by audience and rendered
 * `[0]`; an internal operations document sorted first and served on every vendor's public Help
 * Centre. The fix on that page was one correct filter. This test is the mechanical half: the public
 * counterpart of `tests/operator-doc-coverage.test.ts`.
 *
 * SHAPE. Import-level and whole-file, parsed with the TypeScript compiler — the approach
 * `tests/repository-purity.test.ts` takes — so a comment or a string naming the module cannot trip
 * it, and every import form is seen: static (type-only included, since a type import is still a
 * signal someone is building on the corpus), `export ... from`, dynamic `import()` and `require()`.
 * Only files whose text mentions `runbook/docs` reach the parser; no other file can name the module.
 *
 * SCOPE. Everything under `app/`, `components/`, `lib/` and `features/`. Files under `app/(admin)/`
 * are staff surfaces and may import it (the runbook page does). The single other exemption is the
 * helper itself. There is no allowlist beyond that, deliberately: a new public surface needing a
 * document gets a new helper function beside `getPublicShopperGuide`, not an exemption here.
 */

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const ROOTS = ["app", "components", "lib", "features"];
const HELPER = "lib/public-docs.ts";
const STAFF_PREFIX = "app/(admin)/";

/** True when a module specifier names the generated docs module, however it is spelled. */
function isDocsModuleSpecifier(specifier: string): boolean {
  const withoutExtension = specifier.replace(/\.(tsx?|jsx?|mjs|cjs)$/, "");
  return (
    withoutExtension === "staff/runbook/docs" || withoutExtension.endsWith("/staff/runbook/docs")
  );
}

/** Every module specifier in `source` that names the generated docs module. */
function findDocsImports(fileName: string, source: string): string[] {
  // Every specifier `isDocsModuleSpecifier` accepts contains this text, so a file without it cannot
  // import the module and is not worth a parse. Parsing every file under the four roots took ~2.3s
  // alone and exceeded vitest's 5s default under a loaded full-suite run (#1022 /fix). The compiler
  // still decides for every file that does mention it — a comment or a string still does not count.
  if (!source.includes("runbook/docs")) return [];
  const sourceFile = ts.createSourceFile(fileName, source, ts.ScriptTarget.Latest, true);
  const found: string[] = [];

  const visit = (node: ts.Node) => {
    let specifier: ts.Expression | undefined;

    if (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) {
      specifier = node.moduleSpecifier;
    } else if (ts.isCallExpression(node)) {
      const isDynamicImport = node.expression.kind === ts.SyntaxKind.ImportKeyword;
      const isRequire = ts.isIdentifier(node.expression) && node.expression.text === "require";
      if (isDynamicImport || isRequire) specifier = node.arguments[0];
    }

    if (specifier && ts.isStringLiteralLike(specifier) && isDocsModuleSpecifier(specifier.text)) {
      found.push(specifier.text);
    }
    ts.forEachChild(node, visit);
  };

  visit(sourceFile);
  return found;
}

function sourceFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return entry.name === "node_modules" ? [] : sourceFiles(path);
    return /\.tsx?$/.test(entry.name) ? [path] : [];
  });
}

function toRepoPath(path: string): string {
  return relative(REPO_ROOT, path).split(sep).join("/");
}

describe("public docs boundary (#1022)", () => {
  describe("the detector", () => {
    const flagged = (source: string) => findDocsImports("probe.tsx", source);

    it("flags a relative static import", () => {
      expect(
        flagged(`import { DOC_ARTICLES } from "../../(admin)/staff/runbook/docs";`),
      ).toHaveLength(1);
    });

    it("flags an @/ alias import, with or without an extension", () => {
      expect(
        flagged(`import { DOC_ARTICLES } from "@/app/(admin)/staff/runbook/docs";`),
      ).toHaveLength(1);
      expect(
        flagged(`import { DOC_ARTICLES } from "@/app/(admin)/staff/runbook/docs.ts";`),
      ).toHaveLength(1);
    });

    it("flags a type-only import", () => {
      expect(flagged(`import type { X } from "@/app/(admin)/staff/runbook/docs";`)).toHaveLength(1);
    });

    it("flags a re-export", () => {
      expect(
        flagged(`export { DOC_ARTICLES } from "@/app/(admin)/staff/runbook/docs";`),
      ).toHaveLength(1);
    });

    it("flags a dynamic import and a require", () => {
      expect(flagged(`const m = await import("@/app/(admin)/staff/runbook/docs");`)).toHaveLength(
        1,
      );
      expect(flagged(`const m = require("../staff/runbook/docs");`)).toHaveLength(1);
    });

    it("does not flag a mention in a comment or a plain string", () => {
      expect(
        flagged(`// see app/(admin)/staff/runbook/docs\nconst note = "staff/runbook/docs";`),
      ).toHaveLength(0);
    });

    it("does not flag a module that merely shares a suffix", () => {
      expect(flagged(`import x from "@/lib/staff/runbook/docs-helper";`)).toHaveLength(0);
    });
  });

  const files = ROOTS.flatMap((root) => sourceFiles(join(REPO_ROOT, root)));

  it("finds source files to check", () => {
    // A walk that silently matches nothing is a test that always passes.
    expect(files.length).toBeGreaterThan(100);
  });

  it("no non-staff file other than lib/public-docs.ts imports the generated docs module", () => {
    const violations = files
      .map(toRepoPath)
      .filter((path) => !path.startsWith(STAFF_PREFIX) && path !== HELPER)
      .flatMap((path) =>
        findDocsImports(path, readFileSync(join(REPO_ROOT, path), "utf8")).map(
          (specifier) => `  ${path} imports ${specifier}`,
        ),
      );

    expect(
      violations,
      `Only ${HELPER} may import the generated KMS corpus outside app/(admin)/ — it holds internal ` +
        `documents. Add a function to ${HELPER} that selects the public article by id instead:\n` +
        violations.join("\n"),
    ).toEqual([]);
  });

  it("the helper is the one exempt importer, and it does import the module", () => {
    // If the helper stopped importing it, the exemption would be dead weight hiding nothing.
    const helperSource = readFileSync(join(REPO_ROOT, HELPER), "utf8");
    expect(findDocsImports(HELPER, helperSource)).toHaveLength(1);
  });
});
