/**
 * The job scheduler (P9.2, #618).
 *
 * A clock and an authenticated fetch. Nothing else lives here.
 *
 * WHY THIS WORKER EXISTS AT ALL. `.open-next/worker.js` is generated by
 * `opennextjs-cloudflare build` and gitignored, and it exports only `fetch` plus
 * three Durable Object classes. There is no `scheduled` export to attach a Cron
 * Trigger to, and editing the generated entry is pointless because the next
 * build overwrites it. So the trigger lives in a second, minimal Worker that
 * calls back into the application over HTTP.
 *
 * WHY IT STAYS DUMB. Every piece of domain logic — which orders are stale, what
 * the payment provider said, whether an order may be cancelled — runs inside the
 * application Worker, on the proven OpenNext runtime where Prisma's WASM query
 * compiler already works. This Worker holds no database access and no domain
 * knowledge, so it can never disagree with the application about any of it, and
 * whether Prisma loads outside OpenNext is a question this design never has to
 * ask.
 *
 * WHY THE JOB LIST IS A LITERAL. A config-driven list would make a typo'd path
 * silently schedule nothing — a failure with no error and no output. As an array
 * in source, adding or renaming a job is a reviewable diff.
 */

interface Env {
  /** Origin of the application Worker, e.g. `https://staging.aheedfoodcentre.nocaped.com`. */
  APP_BASE_URL: string;
  /** Shared secret proving to the application that an invocation came from here. */
  JOB_INVOCATION_TOKEN: string;
}

/** Every path invoked on each tick, in order. */
const JOBS: readonly string[] = ["/api/jobs/reconcile-payments"];

const JOB_TOKEN_HEADER = "x-job-token";

async function invoke(env: Env, path: string): Promise<void> {
  const url = `${env.APP_BASE_URL}${path}`;

  let response: Response;
  try {
    response = await fetch(url, {
      method: "POST",
      headers: { [JOB_TOKEN_HEADER]: env.JOB_INVOCATION_TOKEN },
    });
  } catch (error) {
    // Never rethrow: one unreachable job must not stop the rest of the tick.
    console.error(
      `scheduled job ${path} could not be reached: ${error instanceof Error ? error.message : String(error)}`,
    );
    return;
  }

  if (!response.ok) {
    console.error(`scheduled job ${path} returned ${response.status}`);
    return;
  }

  // The body is the job's own summary. Logged whole because it is small,
  // structured, and the only record of what a tick actually did.
  console.log(`scheduled job ${path} ok: ${await response.text()}`);
}

const scheduler = {
  async scheduled(_controller: ScheduledController, env: Env, _ctx: ExecutionContext) {
    // Sequential, not Promise.all: the job list is short, and a tick that runs
    // them in order keeps the log readable and the load on the app Worker flat.
    for (const path of JOBS) {
      await invoke(env, path);
    }
  },
};

export default scheduler;
