-- P8.5d — Multi-buy tier pricing (#348).
--
-- Generated by `prisma migrate diff` from the datamodel. Every statement below
-- comes from the `ProductPriceTier` declaration in schema.prisma, so the schema
-- still describes the database in full and there is no hand-authored DDL here.
--
-- THREE `DROP INDEX` STATEMENTS WERE DELIBERATELY REMOVED from the generated
-- output before saving it:
--
--   DROP INDEX "Order_guestEmail_trgm_idx";
--   DROP INDEX "Order_orderNumber_trgm_idx";
--   DROP INDEX "User_email_trgm_idx";
--
-- Those are the pg_trgm trigram indexes created by
-- 20260820143949_p7_5de_order_search_trigram. Prisma's schema language cannot
-- express a trigram index, so the datamodel does not know they exist and every
-- `migrate diff` proposes dropping them. This is the exact failure mode
-- CLAUDE.md's "hand-authored DDL in a migration" rule warns about — drift that
-- is not drift. Applying them would silently destroy order/customer search.
--
-- If you regenerate this migration, strip those three lines again.

-- CreateTable
CREATE TABLE "ProductPriceTier" (
    "id" TEXT NOT NULL,
    "vendorId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "groupQuantity" INTEGER NOT NULL,
    "groupPricePence" INTEGER NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ProductPriceTier_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ProductPriceTier_productId_key" ON "ProductPriceTier"("productId");

-- CreateIndex
CREATE INDEX "ProductPriceTier_vendorId_isActive_idx" ON "ProductPriceTier"("vendorId", "isActive");

-- CreateIndex
CREATE UNIQUE INDEX "ProductPriceTier_vendorId_productId_key" ON "ProductPriceTier"("vendorId", "productId");

-- AddForeignKey
ALTER TABLE "ProductPriceTier" ADD CONSTRAINT "ProductPriceTier_vendorId_fkey" FOREIGN KEY ("vendorId") REFERENCES "Vendor"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProductPriceTier" ADD CONSTRAINT "ProductPriceTier_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
